services:
  redis:
    image: redis:alpine
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_URL=${REDIS_URL}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./.env:/app/.env
      - "/mnt/c/Users/FunnyRockfish/GO_from_Beginner_to_9 dan_10000:/data/tasks:ro"
    depends_on:
      - redis
      - mongo
  nginx:
    image: nginx:1.27.4
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     # - /home/ubuntu/game/go-game-front/dist:/dist
    ports:
      - '${NGINX_SERVER_PORT}:80'
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongo-data:
