services:
  redis:
    image: redis:alpine
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - REDIS_URL=redis:6379
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - redis