package errors

import (
	"errors"
)

var (
	ErrUserNotFound           = errors.New("user with provided username was not found")
	ErrWrongPassword          = errors.New("wrong password")
	ErrSessionNotFound        = errors.New("session was not found")
	ErrCreateGameFailed       = errors.New("create game failed")
	ErrJoinGameFailed         = errors.New("join game failed")
	ErrGameNotFound           = errors.New("game not found")
	ErrUserExists             = errors.New("user already exists")
	ErrInternal               = errors.New("internal error")
	ErrUserAlreadyInGame      = errors.New("user already in game")
	ErrGameKeyGeneration      = errors.New("game key generation failed")
	ErrCheckKeyUniq           = errors.New("check public key uniqueness failed")
	ErrGameInsert             = errors.New("insert game failed")
	ErrAddPlayer              = errors.New("add player failed")
	ErrNoFreeColor            = errors.New("no free color")
	ErrGameLookup             = errors.New("lookup game by public key failed")
	ErrLeaveGame              = errors.New("leave game failed")
	ErrInvalidGameKey         = errors.New("invalid game key")
	ErrGameArchiveNotFound    = errors.New("game not found in archive")
	ErrGameArchiveLookup      = errors.New("lookup game in archive failed")
	ErrSGFNotFound            = errors.New("sgf not found in redis")
	ErrRedis                  = errors.New("redis operation failed")
	ErrGetAllActiveGames      = errors.New("fetch active games failed")
	ErrDecodeGame             = errors.New("decode game failed")
	ErrMongo                  = errors.New("mongodb operation failed")
	ErrArchiveCount           = errors.New("count archive games failed")
	ErrArchiveFetch           = errors.New("fetch archive games failed")
	ErrArchiveDecode          = errors.New("decode archive games failed")
	ErrArchiveAggregate       = errors.New("aggregate archive years/names failed")
	ErrArchiveAggregateDecode = errors.New("decode archive aggregate result failed")
	ErrInvalidArchiveID       = errors.New("invalid archive game id")
	ErrArchiveNotFound        = errors.New("archive game not found")
	ErrGetArchiveByID         = errors.New("fetch archive game by id failed")
	ErrCompleteGame           = errors.New("complete game failed")
	ErrRedisDel               = errors.New("redis delete failed")
	ErrSaveSGF                = errors.New("save sgf to mongo failed")
	ErrSaveMoves              = errors.New("save moves to mongo failed")
)
