// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: katago.proto

package katago

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotMove       string                 `protobuf:"bytes,1,opt,name=bot_move,json=botMove,proto3" json:"bot_move,omitempty"`
	Diagnostics   *Diagnostics           `protobuf:"bytes,2,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotResponse) Reset() {
	*x = BotResponse{}
	mi := &file_katago_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotResponse) ProtoMessage() {}

func (x *BotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_katago_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotResponse.ProtoReflect.Descriptor instead.
func (*BotResponse) Descriptor() ([]byte, []int) {
	return file_katago_proto_rawDescGZIP(), []int{0}
}

func (x *BotResponse) GetBotMove() string {
	if x != nil {
		return x.BotMove
	}
	return ""
}

func (x *BotResponse) GetDiagnostics() *Diagnostics {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *BotResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Diagnostics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BestTen       []*MovePSV             `protobuf:"bytes,1,rep,name=best_ten,json=bestTen,proto3" json:"best_ten,omitempty"`
	BotMove       string                 `protobuf:"bytes,2,opt,name=bot_move,json=botMove,proto3" json:"bot_move,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	WinProb       float64                `protobuf:"fixed64,4,opt,name=win_prob,json=winProb,proto3" json:"win_prob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostics) Reset() {
	*x = Diagnostics{}
	mi := &file_katago_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostics) ProtoMessage() {}

func (x *Diagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_katago_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostics.ProtoReflect.Descriptor instead.
func (*Diagnostics) Descriptor() ([]byte, []int) {
	return file_katago_proto_rawDescGZIP(), []int{1}
}

func (x *Diagnostics) GetBestTen() []*MovePSV {
	if x != nil {
		return x.BestTen
	}
	return nil
}

func (x *Diagnostics) GetBotMove() string {
	if x != nil {
		return x.BotMove
	}
	return ""
}

func (x *Diagnostics) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Diagnostics) GetWinProb() float64 {
	if x != nil {
		return x.WinProb
	}
	return 0
}

type MovePSV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          string                 `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	Psv           int32                  `protobuf:"varint,2,opt,name=psv,proto3" json:"psv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePSV) Reset() {
	*x = MovePSV{}
	mi := &file_katago_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePSV) ProtoMessage() {}

func (x *MovePSV) ProtoReflect() protoreflect.Message {
	mi := &file_katago_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePSV.ProtoReflect.Descriptor instead.
func (*MovePSV) Descriptor() ([]byte, []int) {
	return file_katago_proto_rawDescGZIP(), []int{2}
}

func (x *MovePSV) GetMove() string {
	if x != nil {
		return x.Move
	}
	return ""
}

func (x *MovePSV) GetPsv() int32 {
	if x != nil {
		return x.Psv
	}
	return 0
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Coordinates   string                 `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_katago_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_katago_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_katago_proto_rawDescGZIP(), []int{3}
}

func (x *Move) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Move) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

type Moves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*Move                `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moves) Reset() {
	*x = Moves{}
	mi := &file_katago_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moves) ProtoMessage() {}

func (x *Moves) ProtoReflect() protoreflect.Message {
	mi := &file_katago_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moves.ProtoReflect.Descriptor instead.
func (*Moves) Descriptor() ([]byte, []int) {
	return file_katago_proto_rawDescGZIP(), []int{4}
}

func (x *Moves) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

var File_katago_proto protoreflect.FileDescriptor

var file_katago_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x6b, 0x61, 0x74, 0x61, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6b, 0x61, 0x74, 0x61, 0x67, 0x6f, 0x22, 0x7e, 0x0a, 0x0b, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x74, 0x5f, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x74, 0x4d, 0x6f, 0x76, 0x65,
	0x12, 0x35, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x61, 0x74, 0x61, 0x67, 0x6f, 0x2e, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x44, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x62, 0x65, 0x73, 0x74, 0x5f, 0x74,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6b, 0x61, 0x74, 0x61, 0x67,
	0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x53, 0x56, 0x52, 0x07, 0x62, 0x65, 0x73, 0x74, 0x54,
	0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x74, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x22, 0x2f,
	0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x53, 0x56, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x73, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x73, 0x76, 0x22,
	0x3e, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22,
	0x2b, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x61, 0x74, 0x61, 0x67, 0x6f,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x32, 0x43, 0x0a, 0x0d,
	0x4b, 0x61, 0x74, 0x61, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x0c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0d, 0x2e,
	0x6b, 0x61, 0x74, 0x61, 0x67, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x1a, 0x13, 0x2e, 0x6b,
	0x61, 0x74, 0x61, 0x67, 0x6f, 0x2e, 0x42, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x6b, 0x61, 0x74, 0x61, 0x67, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_katago_proto_rawDescOnce sync.Once
	file_katago_proto_rawDescData []byte
)

func file_katago_proto_rawDescGZIP() []byte {
	file_katago_proto_rawDescOnce.Do(func() {
		file_katago_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_katago_proto_rawDesc), len(file_katago_proto_rawDesc)))
	})
	return file_katago_proto_rawDescData
}

var file_katago_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_katago_proto_goTypes = []any{
	(*BotResponse)(nil), // 0: katago.BotResponse
	(*Diagnostics)(nil), // 1: katago.Diagnostics
	(*MovePSV)(nil),     // 2: katago.MovePSV
	(*Move)(nil),        // 3: katago.Move
	(*Moves)(nil),       // 4: katago.Moves
}
var file_katago_proto_depIdxs = []int32{
	1, // 0: katago.BotResponse.diagnostics:type_name -> katago.Diagnostics
	2, // 1: katago.Diagnostics.best_ten:type_name -> katago.MovePSV
	3, // 2: katago.Moves.moves:type_name -> katago.Move
	4, // 3: katago.KatagoService.GenerateMove:input_type -> katago.Moves
	0, // 4: katago.KatagoService.GenerateMove:output_type -> katago.BotResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_katago_proto_init() }
func file_katago_proto_init() {
	if File_katago_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_katago_proto_rawDesc), len(file_katago_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_katago_proto_goTypes,
		DependencyIndexes: file_katago_proto_depIdxs,
		MessageInfos:      file_katago_proto_msgTypes,
	}.Build()
	File_katago_proto = out.File
	file_katago_proto_goTypes = nil
	file_katago_proto_depIdxs = nil
}
