// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: katago.proto

package katago

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KatagoService_GenerateMove_FullMethodName = "/katago.KatagoService/GenerateMove"
)

// KatagoServiceClient is the client API for KatagoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KatagoServiceClient interface {
	GenerateMove(ctx context.Context, in *Moves, opts ...grpc.CallOption) (*BotResponse, error)
}

type katagoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKatagoServiceClient(cc grpc.ClientConnInterface) KatagoServiceClient {
	return &katagoServiceClient{cc}
}

func (c *katagoServiceClient) GenerateMove(ctx context.Context, in *Moves, opts ...grpc.CallOption) (*BotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, KatagoService_GenerateMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KatagoServiceServer is the server API for KatagoService service.
// All implementations must embed UnimplementedKatagoServiceServer
// for forward compatibility.
type KatagoServiceServer interface {
	GenerateMove(context.Context, *Moves) (*BotResponse, error)
	mustEmbedUnimplementedKatagoServiceServer()
}

// UnimplementedKatagoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKatagoServiceServer struct{}

func (UnimplementedKatagoServiceServer) GenerateMove(context.Context, *Moves) (*BotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMove not implemented")
}
func (UnimplementedKatagoServiceServer) mustEmbedUnimplementedKatagoServiceServer() {}
func (UnimplementedKatagoServiceServer) testEmbeddedByValue()                       {}

// UnsafeKatagoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KatagoServiceServer will
// result in compilation errors.
type UnsafeKatagoServiceServer interface {
	mustEmbedUnimplementedKatagoServiceServer()
}

func RegisterKatagoServiceServer(s grpc.ServiceRegistrar, srv KatagoServiceServer) {
	// If the following call pancis, it indicates UnimplementedKatagoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KatagoService_ServiceDesc, srv)
}

func _KatagoService_GenerateMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Moves)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KatagoServiceServer).GenerateMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KatagoService_GenerateMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KatagoServiceServer).GenerateMove(ctx, req.(*Moves))
	}
	return interceptor(ctx, in, info, handler)
}

// KatagoService_ServiceDesc is the grpc.ServiceDesc for KatagoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KatagoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "katago.KatagoService",
	HandlerType: (*KatagoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateMove",
			Handler:    _KatagoService_GenerateMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "katago.proto",
}
