// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/JoinGame": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Lets a user join an existing game by public key and role. Requires authentication via cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Join a game",
                "parameters": [
                    {
                        "description": "Join game parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.GameJoinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully joined",
                        "schema": {
                            "$ref": "#/definitions/game.JsonOKResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request or game not found",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/NewGame": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a new Go game with the specified board size, komi and creator color. Requires authentication via cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Create a new game",
                "parameters": [
                    {
                        "description": "New game parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game successfully created",
                        "schema": {
                            "$ref": "#/definitions/game.GameCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing or invalid parameters)",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/analyseCurrent": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Sends current game SGF to KataGo for analysis. Requires authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Analyse current game state",
                "parameters": [
                    {
                        "description": "Public key of current game",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.AnalyseGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "KataGo analysis results",
                        "schema": {
                            "$ref": "#/definitions/game.KataGoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request or analysis error",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getArchive": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a page of archived games, filterable by year or player name (at least one required).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "List archived games with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by year (required if name not set)",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by player name (required if year not set)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 0)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of archived games",
                        "schema": {
                            "$ref": "#/definitions/game.ArchiveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request or archive retrieval error",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getAvailableGamesForUser": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a paginated list of tasks at the specified difficulty level, marking each as done or not_done.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get available tasks for a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Task difficulty level",
                        "name": "level",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/task.TaskResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized\"                     // if no valid user cookie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "416": {
                        "description": "Requested Range Not Satisfiable\"  // e.g. missing or invalid parameters",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getGameByPublicKey": {
            "post": {
                "description": "Returns detailed information about a game given its public key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Retrieve game by public key",
                "parameters": [
                    {
                        "description": "Game public key",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.GetGameInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game information",
                        "schema": {
                            "$ref": "#/definitions/game.GetGameInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request or invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/getGameFromArchiveById": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the archived game record for the given archive document ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Retrieve a single archived game by ID",
                "parameters": [
                    {
                        "description": "Archive document ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.FindGameInArchive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Archived game details",
                        "schema": {
                            "$ref": "#/definitions/game.GameFromArchive"
                        }
                    },
                    "400": {
                        "description": "Bad request or invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getNamesInArchive": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a paginated list of player names sorted by game count.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "List most frequent players in archive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of player names",
                        "schema": {
                            "$ref": "#/definitions/game.ArchiveNamesResponse"
                        }
                    },
                    "400": {
                        "description": "Error retrieving names",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/getUserById": {
            "post": {
                "description": "Возвращает пользователя по ID. Требуется авторизация (cookie sessionID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение информации о пользователе",
                "parameters": [
                    {
                        "description": "ID пользователя для поиска",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserFindRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Only POST method is allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getYearsInArchive": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a sorted list of years for which archived games exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "List available archive years",
                "responses": {
                    "200": {
                        "description": "Array of years",
                        "schema": {
                            "$ref": "#/definitions/game.ArchiveYearsResponse"
                        }
                    },
                    "400": {
                        "description": "Error retrieving years",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/leaveGame": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Allows a user to leave a game by its public key. Requires authentication via cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Leave a game",
                "parameters": [
                    {
                        "description": "Game public key",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.GameLeaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully left the game",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request or invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Авторизует пользователя по логину и паролю, устанавливает cookie sessionID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя для входа",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Удаляет сессию пользователя по cookie sessionID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/markTaskAsDone": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Marks the task with the given ID as completed in the user's record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Mark a task as done for the current user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unique identifier of the task to mark as done",
                        "name": "taskID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized\"                     // if no valid user cookie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "416": {
                        "description": "Requested Range Not Satisfiable\"  // e.g. missing or invalid taskID",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Создаёт нового пользователя и устанавливает cookie sessionID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя для регистрации",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/startGame": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Upgrades the HTTP connection to WebSocket for live move exchange. Query param ` + "`" + `game_id` + "`" + ` required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Start real‑time game via WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public key of the game to join via WS",
                        "name": "game_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Initial game state or move update",
                        "schema": {
                            "$ref": "#/definitions/game.GameStateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing game_id)",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden (not a player)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found (game not found)",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storeTasksToMongoByPath": {
            "get": {
                "description": "Reads all ` + "`" + `.sgf` + "`" + ` files from the given path and saves them into the MongoDB ` + "`" + `tasks` + "`" + ` collection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Store tasks in MongoDB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filesystem path to directory containing SGF files",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully stored tasks in MongoDB",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "416": {
                        "description": "Requested Range Not Satisfiable\"  // e.g. error during file processing or Mongo insert",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string"
                },
                "Password": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "auth.UserFindRequest": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "game.AnalyseGameRequest": {
            "type": "object",
            "properties": {
                "game_public_key": {
                    "type": "string"
                }
            }
        },
        "game.ArchiveNamesResponse": {
            "type": "object",
            "properties": {
                "names": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.NameGameStruct"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages_total": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "game.ArchiveResponse": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.GameFromArchive"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages_total": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "game.ArchiveYearsResponse": {
            "type": "object",
            "properties": {
                "years": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.YearGameStruct"
                    }
                }
            }
        },
        "game.CreateGameRequest": {
            "type": "object",
            "properties": {
                "board_size": {
                    "type": "integer"
                },
                "is_creator_black": {
                    "type": "boolean"
                },
                "komi": {
                    "type": "number"
                },
                "rules": {
                    "type": "string"
                }
            }
        },
        "game.FindGameInArchive": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "string"
                }
            }
        },
        "game.Game": {
            "type": "object",
            "properties": {
                "board_size": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_turn": {
                    "type": "string"
                },
                "game_key": {
                    "description": "уникальный ключ",
                    "type": "string"
                },
                "game_key_public": {
                    "type": "string"
                },
                "komi": {
                    "type": "number"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.Move"
                    }
                },
                "player_black": {
                    "type": "string"
                },
                "player_white": {
                    "type": "string"
                },
                "rules": {
                    "type": "string"
                },
                "sgf": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.GameUser"
                    }
                },
                "who_is_next": {
                    "description": "color",
                    "type": "string"
                }
            }
        },
        "game.GameCreateResponse": {
            "type": "object",
            "properties": {
                "public_key": {
                    "type": "string"
                }
            }
        },
        "game.GameFromArchive": {
            "type": "object",
            "properties": {
                "blackPlayer": {
                    "type": "string"
                },
                "blackRank": {
                    "type": "string"
                },
                "boardSize": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "game_id": {
                    "type": "string"
                },
                "komi": {
                    "type": "number"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.Move"
                    }
                },
                "result": {
                    "$ref": "#/definitions/game.Result"
                },
                "rules": {
                    "type": "string"
                },
                "sgf": {
                    "type": "string"
                },
                "whitePlayer": {
                    "type": "string"
                },
                "whiteRank": {
                    "type": "string"
                }
            }
        },
        "game.GameJoinRequest": {
            "type": "object",
            "properties": {
                "public_key": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "game.GameLeaveRequest": {
            "type": "object",
            "properties": {
                "public_key": {
                    "type": "string"
                }
            }
        },
        "game.GameStateResponse": {
            "type": "object",
            "properties": {
                "move": {
                    "$ref": "#/definitions/game.Move"
                },
                "move_info": {
                    "$ref": "#/definitions/game.MoveInfoWS"
                }
            }
        },
        "game.GameUser": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "role": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "game.GetGameInfoRequest": {
            "type": "object",
            "properties": {
                "game_key": {
                    "type": "string"
                }
            }
        },
        "game.GetGameInfoResponse": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/game.Game"
                },
                "player_black_nickname": {
                    "type": "string"
                },
                "player_white_nickname": {
                    "type": "string"
                }
            }
        },
        "game.JsonOKResponse": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "game.KataGoResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDuringSearch": {
                    "type": "boolean"
                },
                "moveInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.MoveInfo"
                    }
                },
                "ownership": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "policy": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "rootInfo": {
                    "$ref": "#/definitions/game.RootInfo"
                },
                "turnNumber": {
                    "type": "integer"
                }
            }
        },
        "game.Move": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "coordinates": {
                    "type": "string"
                }
            }
        },
        "game.MoveInfo": {
            "type": "object",
            "properties": {
                "edgeVisits": {
                    "type": "integer"
                },
                "edgeWeight": {
                    "type": "number"
                },
                "lcb": {
                    "type": "number"
                },
                "move": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "prior": {
                    "type": "number"
                },
                "pv": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scoreLead": {
                    "type": "number"
                },
                "scoreMean": {
                    "type": "number"
                },
                "scoreSelfplay": {
                    "type": "number"
                },
                "scoreStdev": {
                    "type": "number"
                },
                "utility": {
                    "type": "number"
                },
                "utilityLcb": {
                    "type": "number"
                },
                "visits": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                },
                "winrate": {
                    "type": "number"
                }
            }
        },
        "game.MoveInfoWS": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "isGameFinished": {
                    "type": "boolean"
                },
                "isMoveCorrect": {
                    "type": "boolean"
                },
                "newSgf": {
                    "type": "string"
                }
            }
        },
        "game.NameGameStruct": {
            "type": "object",
            "properties": {
                "count_of_games": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "game.Result": {
            "type": "object",
            "properties": {
                "pointDiff": {
                    "type": "number"
                },
                "winColor": {
                    "type": "string"
                }
            }
        },
        "game.RootInfo": {
            "type": "object",
            "properties": {
                "currentPlayer": {
                    "type": "string"
                },
                "rawLead": {
                    "type": "number"
                },
                "rawNoResultProb": {
                    "type": "number"
                },
                "rawScoreSelfplay": {
                    "type": "number"
                },
                "rawScoreSelfplayStdev": {
                    "type": "number"
                },
                "rawStScoreError": {
                    "type": "number"
                },
                "rawStWrError": {
                    "type": "number"
                },
                "rawVarTimeLeft": {
                    "type": "number"
                },
                "rawWinrate": {
                    "type": "number"
                },
                "scoreLead": {
                    "type": "number"
                },
                "scoreSelfplay": {
                    "type": "number"
                },
                "scoreStdev": {
                    "type": "number"
                },
                "symHash": {
                    "type": "string"
                },
                "thisHash": {
                    "type": "string"
                },
                "utility": {
                    "type": "number"
                },
                "visits": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                },
                "winrate": {
                    "type": "number"
                }
            }
        },
        "game.YearGameStruct": {
            "type": "object",
            "properties": {
                "count_of_games": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "httpresponse.ErrorResponse": {
            "type": "object",
            "properties": {
                "ErrorDescription": {
                    "type": "string"
                }
            }
        },
        "task.Task": {
            "type": "object",
            "properties": {
                "task_level": {
                    "description": "Difficulty level (chapter index) of the task\nrequired: true\nexample: 3",
                    "type": "integer"
                },
                "task_number": {
                    "description": "Unique identifier for this task\nrequired: true\nexample: 42",
                    "type": "integer"
                },
                "task_sgf": {
                    "description": "Raw SGF content of the problem\nrequired: true\nexample: \"(;SZ[19]... )\"",
                    "type": "string"
                },
                "task_status": {
                    "description": "Current status, one of \"done\" or \"not_done\"\nrequired: true\nexample: \"not_done\"",
                    "type": "string"
                }
            }
        },
        "task.TaskResponse": {
            "type": "object",
            "properties": {
                "page_tmp": {
                    "description": "Current page number (1-based)\nrequired: true\nexample: 1",
                    "type": "integer"
                },
                "page_with_unresolved": {
                    "description": "First page that still contains not_done tasks\nrequired: true\nexample: 1",
                    "type": "integer"
                },
                "tasks": {
                    "description": "Tasks on this page\nrequired: true",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/task.Task"
                    }
                },
                "total_pages": {
                    "description": "Total number of pages available\nrequired: true\nexample: 5",
                    "type": "integer"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "Username": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "coins": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_game_key": {
                    "type": "string"
                },
                "done_tasks_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "passwordHash": {
                    "type": "string"
                },
                "passwordSalt": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "social_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "statistic": {
                    "$ref": "#/definitions/user.UserStatistic"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "user.UserStatistic": {
            "type": "object",
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "draws": {
                    "type": "integer"
                },
                "losses": {
                    "type": "integer"
                },
                "wins": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "sessionID",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "",
	Description:      "Документация API авторизации и пользователей",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
