// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/JoinGame": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет пользователя в игру по публичному ключу. Нужна авторизация.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Присоединиться к существующей игре",
                "parameters": [
                    {
                        "description": "Ключ и роль",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.GameJoinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "400": {
                        "description": "Игра не найдена / пользователь уже в игре",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/NewGame": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Регистрирует новую запись в базе и отдаёт публичный ключ партии. Нужна авторизация.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Создать новую игру человека против человека",
                "parameters": [
                    {
                        "description": "Параметры игры",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/game.GameCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибочные параметры или пользователь уже в игре",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Нет cookie sessionID",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/analyseCurrent": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Отправляет SGF текущей игры в KataGo для анализа. Если ключ не передан, будет использована активная игра пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Анализ текущего состояния игры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ключ игры (secret, опционально)",
                        "name": "secret_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результаты анализа от KataGo",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpresponse.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Body": {
                                            "$ref": "#/definitions/game.KataGoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Ошибка запроса или анализа игры",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "405": {
                        "description": "Метод не разрешён",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/generateMove": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обрабатывает ход пользователя, генерирует ответный ход бота и возвращает обновлённый список ходов и SGF партии.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Сгенерировать ход против бота",
                "parameters": [
                    {
                        "description": "Ход пользователя",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.GenerateMoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список ходов и новый SGF",
                        "schema": {
                            "$ref": "#/definitions/game.BotGenerateMoveResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный JSON или ошибка логики игры",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/getArchive": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает страницу архивных игр с возможностью фильтрации по году или имени игрока (один из параметров обязателен).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получить список игр из архива с пагинацией",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Фильтр по году (если не указан фильтр по имени)",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по имени игрока (если не указан год)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы (по умолчанию 0)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Страница архивных игр",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpresponse.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Body": {
                                            "$ref": "#/definitions/game.ArchiveResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос или ошибка получения архива",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "405": {
                        "description": "Метод не разрешён",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/getAvailableGamesForUser": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает постраничный список задач указанного уровня сложности с пометкой «решена/нет».",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Список задач пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Номер страницы (1‑based)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Уровень сложности",
                        "name": "level",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/task.TaskResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "416": {
                        "description": "Некорректные параметры",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/getGameByPublicKey": {
            "post": {
                "description": "Возвращает подробную информацию об игре по её публичному ключу.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получить игру по публичному ключу",
                "parameters": [
                    {
                        "description": "Публичный ключ игры",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.GetGameInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация об игре",
                        "schema": {
                            "$ref": "#/definitions/game.GetGameInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос или ошибка в формате JSON",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/getGameFromArchiveById": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает запись об архивной игре по её идентификатору в архиве.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получить игру из архива по идентификатору",
                "parameters": [
                    {
                        "description": "Идентификатор записи архива",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.FindGameInArchive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные архивной игры",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpresponse.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Body": {
                                            "$ref": "#/definitions/game.GameFromArchive"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос или ошибка поиска игры",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "405": {
                        "description": "Метод не разрешён",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/getNamesInArchive": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает страницу с именами игроков, отсортированными по количеству сыгранных игр.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получить список игроков из архива",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Номер страницы (по умолчанию 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Страница имён игроков",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpresponse.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Body": {
                                            "$ref": "#/definitions/game.ArchiveNamesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Ошибка получения списка имён",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "405": {
                        "description": "Метод не разрешён",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/getUserById": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает пользователя по его ID. Требуется авторизация по cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получить данные пользователя",
                "parameters": [
                    {
                        "description": "ID пользователя",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserFindRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "400": {
                        "description": "Некорректный JSON или пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/getYearsInArchive": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает отсортированный список лет, за которые имеются архивные игры.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Получить список годов в архиве",
                "responses": {
                    "200": {
                        "description": "Список годов",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpresponse.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Body": {
                                            "$ref": "#/definitions/game.ArchiveYearsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Ошибка получения годов",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "405": {
                        "description": "Метод не разрешён",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/leaveGame": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Освобождает слот игрока. Требуется авторизация.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Покинуть игру",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Публичный ключ игры",
                        "name": "public_key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Проверяет логин/пароль и устанавливает cookie ` + "`" + `sessionID` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход пользователя",
                "parameters": [
                    {
                        "description": "Логин и пароль",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "400": {
                        "description": "Пользователь не найден / неверный пароль / плохой JSON",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет сессию, указанную в cookie ` + "`" + `sessionID` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "400": {
                        "description": "Нет cookie или сессия не найдена",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/markTaskAsDone": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет ID задачи в список выполненных пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Отметить задачу как решённую",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "taskID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "416": {
                        "description": "Некорректный taskID",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/newBotGame": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создаёт новую игру против бота и возвращает секретный ключ игры.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Создать новую игру с ботом",
                "parameters": [
                    {
                        "description": "Параметры новой игры с ботом",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.CreateBotGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Секретный ключ игры",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpresponse.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Body": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Ошибка создания игры",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "405": {
                        "description": "Метод не разрешён",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Создаёт нового пользователя и сразу устанавливает cookie ` + "`" + `sessionID` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Учётные данные",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ответ без тела — только Status",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос (например, плохой JSON)",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/startGame": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Апгрейд HTTP→WS для обмена ходами в режиме реального времени. После ответа 101 дальнейшее общение идёт по протоколу WebSocket.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "game"
                ],
                "summary": "WebSocket‑сессия игры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Публичный ключ игры",
                        "name": "game_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Переключение протокола",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        },
        "/storeTasksToMongoByPath": {
            "get": {
                "description": "Рекурсивно читает все файлы ` + "`" + `*.sgf` + "`" + ` по указанному пути и сохраняет их в коллекцию ` + "`" + `tasks` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Загрузить задачи SGF в MongoDB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Путь к директории с SGF",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ОК",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "405": {
                        "description": "Метод не поддерживается",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    },
                    "416": {
                        "description": "Ошибка чтения файлов",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string"
                },
                "Password": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "auth.UserFindRequest": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "game.ArchiveNamesResponse": {
            "type": "object",
            "properties": {
                "names": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.NameGameStruct"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages_total": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "game.ArchiveResponse": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.GameFromArchive"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pages_total": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "game.ArchiveYearsResponse": {
            "type": "object",
            "properties": {
                "years": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.YearGameStruct"
                    }
                }
            }
        },
        "game.BotGenerateMoveResponse": {
            "type": "object",
            "properties": {
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.Move"
                    }
                },
                "sgf": {
                    "type": "string"
                }
            }
        },
        "game.CreateBotGameRequest": {
            "type": "object",
            "properties": {
                "board_size": {
                    "type": "integer"
                },
                "is_creator_black": {
                    "type": "boolean"
                },
                "komi": {
                    "type": "number"
                },
                "rules": {
                    "type": "string"
                }
            }
        },
        "game.CreateGameRequest": {
            "type": "object",
            "properties": {
                "board_size": {
                    "type": "integer"
                },
                "is_creator_black": {
                    "type": "boolean"
                },
                "komi": {
                    "type": "number"
                },
                "rules": {
                    "type": "string"
                }
            }
        },
        "game.FindGameInArchive": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "string"
                }
            }
        },
        "game.Game": {
            "type": "object",
            "properties": {
                "board_size": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_turn": {
                    "type": "string"
                },
                "game_key": {
                    "description": "уникальный ключ",
                    "type": "string"
                },
                "game_key_public": {
                    "type": "string"
                },
                "isFromArchive": {
                    "type": "boolean"
                },
                "komi": {
                    "type": "number"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.Move"
                    }
                },
                "player_black": {
                    "type": "string"
                },
                "player_white": {
                    "type": "string"
                },
                "rules": {
                    "type": "string"
                },
                "sgf": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.GameUser"
                    }
                },
                "who_is_next": {
                    "description": "color",
                    "type": "string"
                }
            }
        },
        "game.GameCreateResponse": {
            "type": "object",
            "properties": {
                "public_key": {
                    "type": "string"
                }
            }
        },
        "game.GameFromArchive": {
            "type": "object",
            "properties": {
                "blackPlayer": {
                    "type": "string"
                },
                "blackRank": {
                    "type": "string"
                },
                "boardSize": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "game_id": {
                    "type": "string"
                },
                "komi": {
                    "type": "number"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.Move"
                    }
                },
                "result": {
                    "$ref": "#/definitions/game.Result"
                },
                "rules": {
                    "type": "string"
                },
                "sgf": {
                    "type": "string"
                },
                "whitePlayer": {
                    "type": "string"
                },
                "whiteRank": {
                    "type": "string"
                }
            }
        },
        "game.GameJoinRequest": {
            "type": "object",
            "properties": {
                "public_key": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "game.GameUser": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "role": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "game.GenerateMoveRequest": {
            "type": "object",
            "properties": {
                "move": {
                    "$ref": "#/definitions/game.Move"
                }
            }
        },
        "game.GetGameInfoRequest": {
            "type": "object",
            "properties": {
                "game_key": {
                    "type": "string"
                }
            }
        },
        "game.GetGameInfoResponse": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/game.Game"
                },
                "player_black_nickname": {
                    "type": "string"
                },
                "player_white_nickname": {
                    "type": "string"
                }
            }
        },
        "game.KataGoResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDuringSearch": {
                    "type": "boolean"
                },
                "moveInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.MoveInfo"
                    }
                },
                "ownership": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "policy": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "rootInfo": {
                    "$ref": "#/definitions/game.RootInfo"
                },
                "turnNumber": {
                    "type": "integer"
                }
            }
        },
        "game.Move": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "coordinates": {
                    "type": "string"
                }
            }
        },
        "game.MoveInfo": {
            "type": "object",
            "properties": {
                "edgeVisits": {
                    "type": "integer"
                },
                "edgeWeight": {
                    "type": "number"
                },
                "lcb": {
                    "type": "number"
                },
                "move": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "prior": {
                    "type": "number"
                },
                "pv": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scoreLead": {
                    "type": "number"
                },
                "scoreMean": {
                    "type": "number"
                },
                "scoreSelfplay": {
                    "type": "number"
                },
                "scoreStdev": {
                    "type": "number"
                },
                "utility": {
                    "type": "number"
                },
                "utilityLcb": {
                    "type": "number"
                },
                "visits": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                },
                "winrate": {
                    "type": "number"
                }
            }
        },
        "game.NameGameStruct": {
            "type": "object",
            "properties": {
                "count_of_games": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "game.Result": {
            "type": "object",
            "properties": {
                "pointDiff": {
                    "type": "number"
                },
                "winColor": {
                    "type": "string"
                }
            }
        },
        "game.RootInfo": {
            "type": "object",
            "properties": {
                "currentPlayer": {
                    "type": "string"
                },
                "rawLead": {
                    "type": "number"
                },
                "rawNoResultProb": {
                    "type": "number"
                },
                "rawScoreSelfplay": {
                    "type": "number"
                },
                "rawScoreSelfplayStdev": {
                    "type": "number"
                },
                "rawStScoreError": {
                    "type": "number"
                },
                "rawStWrError": {
                    "type": "number"
                },
                "rawVarTimeLeft": {
                    "type": "number"
                },
                "rawWinrate": {
                    "type": "number"
                },
                "scoreLead": {
                    "type": "number"
                },
                "scoreSelfplay": {
                    "type": "number"
                },
                "scoreStdev": {
                    "type": "number"
                },
                "symHash": {
                    "type": "string"
                },
                "thisHash": {
                    "type": "string"
                },
                "utility": {
                    "type": "number"
                },
                "visits": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                },
                "winrate": {
                    "type": "number"
                }
            }
        },
        "game.YearGameStruct": {
            "type": "object",
            "properties": {
                "count_of_games": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "httpresponse.ErrorResponse": {
            "type": "object",
            "properties": {
                "ErrorDescription": {
                    "type": "string"
                }
            }
        },
        "httpresponse.Response": {
            "type": "object",
            "properties": {
                "Body": {},
                "Status": {
                    "type": "integer"
                }
            }
        },
        "task.Task": {
            "type": "object",
            "properties": {
                "task_level": {
                    "description": "Difficulty level (chapter index) of the task\nrequired: true\nexample: 3",
                    "type": "integer"
                },
                "task_number": {
                    "description": "Unique identifier for this task\nrequired: true\nexample: 42",
                    "type": "integer"
                },
                "task_sgf": {
                    "description": "Raw SGF content of the problem\nrequired: true\nexample: \"(;SZ[19]... )\"",
                    "type": "string"
                },
                "task_status": {
                    "description": "Current status, one of \"done\" or \"not_done\"\nrequired: true\nexample: \"not_done\"",
                    "type": "string"
                }
            }
        },
        "task.TaskResponse": {
            "type": "object",
            "properties": {
                "page_tmp": {
                    "description": "Current page number (1-based)\nrequired: true\nexample: 1",
                    "type": "integer"
                },
                "page_with_unresolved": {
                    "description": "First page that still contains not_done tasks\nrequired: true\nexample: 1",
                    "type": "integer"
                },
                "tasks": {
                    "description": "Tasks on this page\nrequired: true",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/task.Task"
                    }
                },
                "total_pages": {
                    "description": "Total number of pages available\nrequired: true\nexample: 5",
                    "type": "integer"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "Username": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "coins": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_game_key": {
                    "type": "string"
                },
                "done_tasks_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "passwordHash": {
                    "type": "string"
                },
                "passwordSalt": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "social_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "statistic": {
                    "$ref": "#/definitions/user.UserStatistic"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "user.UserStatistic": {
            "type": "object",
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "draws": {
                    "type": "integer"
                },
                "losses": {
                    "type": "integer"
                },
                "wins": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "sessionID",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "",
	Description:      "Документация API авторизации и пользователей",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
